events {}

http {
    upstream music_nodes {
        server node-1:8000;
        server node-2:8000;
        server node-3:8000;
        server node-4:8000;
        server node-5:8000;
    }

    server {
        listen 8080;

        # Redirect / to /docs for user-friendliness
        location = / {
            return 302 /docs;
        }

        location / {
            proxy_pass http://music_nodes;
        }
    }
}
